"""Type stubs for filetype library."""

def guess_extension(obj: str) -> str | None: ...
def guess_mime(obj: str) -> str | None: ...
def is_image(obj: str) -> bool: ...
def is_video(obj: str) -> bool: ...
