"""Type stubs for filetype module"""

from typing import Optional

class Type:
    extension: str
    mime: str
    
    def __init__(self) -> None: ...

def guess(path: str) -> Optional[Type]: ...
def guess_extension(path: str) -> Optional[str]: ...
def guess_mime(path: str) -> Optional[str]: ...